name: Unit tests
on: [push, pull_request]
jobs:
  eslint:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      - name: Run Tests
        run: npm run test
    