name: Unit tests
on: [push, pull_request]
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
jobs:
  eslint:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: npm ci
      - name: Run Tests
        run: npm run test
    